<!DOCTYPE html>
<html>

<head>
		<title> InchooApp </title>
		<meta charset="UTF-8"></meta>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
		<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Kaushan+Script&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700;900&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="http://localhost/inchooApp/classes/view/css/home.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

</head>

 <script>
      function switchFeeds(evt, divID) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
          tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(divID).style.display = "block";
        evt.currentTarget.className += " active";
      }
      function moveCursorToEnd(el) {
          if (typeof el.selectionStart == "number") {
            el.selectionStart = el.selectionEnd = el.value.length;
          } else if (typeof el.createTextRange != "undefined") {
            el.focus();
            var range = el.createTextRange();
            range.collapse(false);
            range.select();
          }
        }

</script>

<body>

	<header>
  		<div class="headerContainer">
			<a href='http://localhost/inchooApp/profile'> Profile </a>
      		<a class="tablinks active" onclick="switchFeeds(event, 'photosContainer')"> Browse </button>
      		<a class="tablinks" onclick="switchFeeds(event, 'formContainer')">Upload</button>
			<a href='http://localhost/inchooApp/' > Logout </a>
    </div>


	</header>

	<section>


		<?php echo $content ?>

	</section>


	<footer>
	<p> nes </p>

	</footer>
</body>

</html>
