<!DOCTYPE html>
<html>

<head>
		<title> InchooApp </title>
		<meta charset="UTF-8"></meta>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
		<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Kaushan+Script&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700;900&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="http://localhost/inchooApp/classes/view/css/home.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

</head>
<body>

	<header>

	</header>

	<section>

		<?php echo $content ?>

	</section>


	<footer>


	</footer>
</body>

</html>
