<!DOCTYPE html>
<?php
	$controller = HomeController::getControllerInstance();
?>

<html>

	<head>
		<title> Home </title>
		<meta charset="UTF-8"></meta>
		<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Kaushan+Script&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700;900&display=swap" rel="stylesheet"> 
		<link rel="stylesheet" type="text/css" href="./classes/view/css/home.css"></link>
 		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
	</head>

	<script language="JavaScript" type="text/javascript">
  		$(document).ready(function(){
    		$('#myCarousel').carousel({
      		interval: 1500
    		})
  		});

		function countPhotos(){
			var xhttp;
			xhttp = new XMLHttpRequest();
			xhttp.onreadystatechange = function(){
				if (this.readyState == 4 && this.status==200){
					document.getElementById("photoCountContainer").innerHTML = this.responseText;
					var photoCount = document.getElementById("photoCount");
					photoCount.style.color="white";
					photoCount.style.fontWeight="bolder";
					photoCount.style.fontSize="90px";
					photoCount.style.fontFamily="Kaushan script, cursive";
					var max = parseInt(photoCount.innerText);
					photoCount.innerText = "#0";
					setTimeout( function() { animate(0, max); }, 100);

				}
			};
			xhttp.open("GET", "ajaxRequest.php?count=1", true);
			xhttp.send();
		}

		function animate(current, max){
			if (current != max){
				current++;
				document.getElementById("photoCount").innerText = "#".concat(current);
				setTimeout( function() { animate(current, max); }, 60);
			}
			return;				
				
		}
	</script>

	<body>

		<header>
			<div class="headerMainContainer">
				<p>something</p>
			</div>
		</header>

		<section>
			<div class="titleContainer">
				<h id="title" >InchooApp</h>
			</div>

			<div id="myCarousel" class="carousel slide" data-ride="carousel">
    			<!-- Indicators -->
    			<ol class="carousel-indicators">
      				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      				<li data-target="#myCarousel" data-slide-to="1"></li>
      				<li data-target="#myCarousel" data-slide-to="2"></li>
    			</ol>

    			<!-- Wrapper for slides -->
    			<div class="carousel-inner">
      				<div class="item active">
        				<img src="images/universe.jpeg" alt="forest">
						<div class="carousel-caption">
							<p class="moti"> Share your own vision of the universe </p>
						</div>
	 				</div>

      				<div class="item">
        				<img src="images/lake.jpeg" alt="nature">
						<div class="carousel-caption">
							<p class="moti"> Bring along your friends on an advanture </p>
						</div>
      				</div>
    
      				<div class="item">
        				<img src="images/surfer.jpeg" alt="lion">
						<div class="carousel-caption">
							<p class="moti"> Let everyone know of your achievments </p>
						</div>
      				</div>
    			</div>

    			<!-- Left and right controls -->
    			<a class="left carousel-control" href="#myCarousel" data-slide="prev">
      				<span class="glyphicon glyphicon-chevron-left"></span>
      				<span class="sr-only">Previous</span>
    			</a>
    			<a class="right carousel-control" href="#myCarousel" data-slide="next">
      				<span class="glyphicon glyphicon-chevron-right"></span>
      				<span class="sr-only">Next</span>
    			</a>
  			</div>


			
			<div class="formContainer">
				<!--
					Remember me button (use cookies, think about session)
				-->
				<form id="loginForm" action="<?php $controller->login(); ?>" method="post">
					<label id="labelUsername" class="label" for="usernameInput">Username: </label><input type="text" id="usernameInput" name="usernameInput"></input>
					<br><br>
					<label id="labelPassword" class="label" for="passwordInput">Password: </label><input type="text" id="passwordInput" name="passwordInput"></input>
					<br><br><br>
					<input type="Submit" value="Login" id="submitButton">

					<div id="rememberMeContainer" class="rememberRegisterContainer">
						<input type="checkbox" id="rememberMeInput" name="rememberMeInput"></input><label id="labelRememberMe">   Remember me</label>
					</div>

					<div id="registerContainer" class="rememberRegisterContainer">
						<a id="registerButton">Register</a>
					</div>
				</form>

			</div>
			
			<div class="photoCounterButtonContainer"><button id="photoCounterButton"  type="button" onclick="countPhotos()">#Images</button></div>
			<div id="photoCountContainer"></div>
		</section>

		<footer>
			<div id="developerContainer" class="footerContainer">
				<p>Developer: ivinski@foi.hr</p>
			</div>

			<div id="socialContainer" class="footerContainer">
			</div>
		</footer>

	</body>

</html>
