<!DOCTYPE html>
<html>

	<head>
		<title> Home </title>
		<meta charset="UTF-8"></meta>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
		<link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Kaushan+Script&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700;900&display=swap" rel="stylesheet"> 
		<link rel="stylesheet" type="text/css" href="http://localhost/inchooApp/classes/view/css/login.css">
 		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<script src="classes/view/ajax/countPhotos.js"></script>
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
	</head>
	<body>
		<?php echo $msg ?>
		<header>
			<div id="test" class="headerMainContainer">
				<p>something</p>
			</div>

	
		</header>

		<section>
			<div class="titleContainer">
				<a href="http://localhost/inchooApp/"><h id="title" >InchooApp</h></a>
			</div>

			<div id="myCarousel" class="carousel slide" data-ride="carousel">
    			<!-- Indicators -->
    			<ol class="carousel-indicators">
      				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      				<li data-target="#myCarousel" data-slide-to="1"></li>
      				<li data-target="#myCarousel" data-slide-to="2"></li>
    			</ol>

    			<!-- Wrapper for slides -->
    			<div class="carousel-inner">
      				<div class="item active">
        				<img src="http://localhost/inchooApp/images/universe.jpeg" alt="forest">
						<div class="carousel-caption">
							<p class="moti"> Share your own vision of the universe </p>
						</div>
	 				</div>

      				<div class="item">
        				<img src="http://localhost/inchooApp/images/lake.jpeg" alt="nature">
						<div class="carousel-caption">
							<p class="moti"> Bring along your friends on an advanture </p>
						</div>
      				</div>
    
      				<div class="item">
        				<img src="http://localhost/inchooApp/images/surfer.jpeg" alt="lion">
						<div class="carousel-caption">
							<p class="moti"> Let everyone know of your achievments </p>
						</div>
      				</div>
    			</div>

    			<!-- Left and right controls -->
    			<a class="left carousel-control" href="#myCarousel" data-slide="prev">
      				<span class="glyphicon glyphicon-chevron-left"></span>
      				<span class="sr-only">Previous</span>
    			</a>
    			<a class="right carousel-control" href="#myCarousel" data-slide="next">
      				<span class="glyphicon glyphicon-chevron-right"></span>
      				<span class="sr-only">Next</span>
    			</a>
  			</div>

				<?php echo $content ?>

		</section>
		<footer>
			<div id="developerContainer" class="footerContainer">
				<p>Developer: ivinski@foi.hr</p>
			</div>

			<div id="socialContainer" class="footerContainer">
			</div>
		</footer>

	</body>

</html>
