<div class="formContainer">
	<!--
	Remember me button (use cookies, think about session)
	-->
	<form id="loginForm" action="" method="POST">
		<label id="labelUsername" class="label">Username: </label><input type="text" id="usernameInput" name="usernameInput" class="input" value=<?php echo $usernameVal ?>></input>
		<br><br>
		<label id="labelPassword" class="label">Password: </label><input type="password" id="passwordInput" name="passwordInput" class="input"></input>
		<br><br><br>
		<input type="submit" value="Login" id="submitButton">

		<div id="rememberMeContainer" class="rememberRegisterContainer">
		<input type="checkbox" id="rememberMeInput" name="rememberMeInput" checked></input><label id="labelRememberMe">   Remember me</label>
		</div>

		<div id="registerContainer" class="rememberRegisterContainer">
			<a id="registerButton" href="register">Register</a>
		</div>
	</form>

	</div>
		<div class="photoCounterButtonContainer"><button id="photoCounterButton"  type="button" onclick="countPhotos()">#Images</button></div>
	<div id="photoCountContainer"><p id="photoCount">#0</p></div>

</div>
