
<div class="formContainer" id="registerFormContainer">
	<form action="register" method="POST">


		<label class="label">Username: </label><input class="input" type="text" name="usernameInput" value=<?php echo $username ?>></input>
		<br><br>
		<label class="label">e-mail: </label><input class="input" type="text" name="emailInput"value=<?php echo $email ?>></input>
		<br><br>
		<label class="label">Password: </label><input class="input" type="text" name="passwordInput"value=<?php echo $password ?>></input>
		<br><br>
		<label class="label">Repeat password: </label><input class="input" type="text" name="passwordRepeatInput" value=<?php echo $passwordRepeat ?>></input>
		<br><br><br>
		<input id="submitButton" type="Submit" value="Register" ></input>

		<div id="registerContainer" class="rememberRegisterContainer">
			<a id="registerButton" href="login">Login</a>
		</div>
	</form>
</div>

